### ISSUE TITLE
Problem installing in laravel 5.3.29

### ISSUE THREAD

**Issue by bantawa04** [drewjbartlett/wordpress-eloquent#1]
`  Problem 1
    - Installation request for drewjbartlett/wordpress-eloquent ^0.0.2 -> satisfiable by drewjbartlett/wordpress-eloquent[v0.0.2].
    - Conclusion: remove laravel/framework v5.3.29
    - Conclusion: don't install laravel/framework v5.3.29
    - drewjbartlett/wordpress-eloquent v0.0.2 requires illuminate/database 5.4.* -> satisfiable by illuminate/database[v5.4.0, v5.4.9].
    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.3.29
    - don't install illuminate/database v5.4.9|don't install laravel/framework v5.3.29
    - Installation request for laravel/framework (locked at v5.3.29, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.29].`

It would be helpful if the package had backward compability

**Comment by drewjbartlett** [comment]
If you install v0.0.1 you can use laravel 5.3

**Comment by drewjbartlett** [comment]
Closing this unless for now v0.0.1 doesn't work for you.
